-- story_002_seed_dad_pool.sql
-- Seeds the 36 prompts of "Dad, Tell Me Your Story" v1 into story_prompts.
-- Source of truth: stone-harbor-docs/Dad_Story_Series_Prompt_Pool_v1.md
--
-- Convention: order_hint is the pool index (101..115 for L1, 201..215 for L2, etc.)
--             so prompts sort naturally within a depth band when surfaced.
-- All prompts: consumer_slug='stone_harbor', language='en', series_slug='dad'.

insert into public.story_prompts
  (consumer_slug, language, series_slug, prompt_text, depth, themes, est_minutes, re_surface_eligible, order_hint, source_ref)
values
  -- ===== Level 1 — Shore =====
  ('stone_harbor','en','dad',
   'What kind of weather did your family keep around you in those first years?',
   1, ARRAY['origin']::text[], 5, true, 101, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.01'),
  ('stone_harbor','en','dad',
   'Your name has a story. Tell me the part of it you know.',
   1, ARRAY['origin','self']::text[], 4, false, 102, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.02'),
  ('stone_harbor','en','dad',
   'The first hero you chose for yourself. Not the cartoon one — the real one.',
   1, ARRAY['self']::text[], 5, true, 103, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.03'),
  ('stone_harbor','en','dad',
   'Tell me about the day of the week that made the others worth waiting through.',
   1, ARRAY['rhythm']::text[], 4, false, 104, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.04'),
  ('stone_harbor','en','dad',
   'The day you counted toward all year. Tell me about it.',
   1, ARRAY['rhythm']::text[], 4, false, 105, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.05'),
  ('stone_harbor','en','dad',
   'Tell me about your brother. Or your sister. Or the sibling you wished you''d had.',
   1, ARRAY['siblings']::text[], 7, true, 106, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.06'),
  ('stone_harbor','en','dad',
   'Write about something you wanted to be when you grew up. Why that, then.',
   1, ARRAY['self']::text[], 6, true, 107, 'Dad_Story_Series_Prompt_Pool_v1.md#L1.07'),

  -- ===== Level 2 — Wading =====
  ('stone_harbor','en','dad',
   'What did your mother call you? What did your father call you? Were they the same name, or two different boys?',
   2, ARRAY['mother','father']::text[], 5, false, 201, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.01'),
  ('stone_harbor','en','dad',
   'Write about him — not who you became, but who he actually was. The actual boy.',
   2, ARRAY['self']::text[], 6, false, 202, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.02'),
  ('stone_harbor','en','dad',
   'What did you carry with you everywhere? And what did it stand in for?',
   2, ARRAY['self']::text[], 5, true, 203, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.03'),
  ('stone_harbor','en','dad',
   'Write about a moment from when you were small that you still keep somewhere safe.',
   2, ARRAY['memory']::text[], 6, true, 204, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.04'),
  ('stone_harbor','en','dad',
   'Write about your grandparents the way you remember them. Their hands. Their voices. The rooms they kept.',
   2, ARRAY['extended']::text[], 7, true, 205, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.05'),
  ('stone_harbor','en','dad',
   'Tell me about your mother and father''s lives before they became yours.',
   2, ARRAY['mother','father']::text[], 8, false, 206, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.06'),
  ('stone_harbor','en','dad',
   'Tell me about the family beyond your house — the ones who didn''t sleep there but who shaped you anyway.',
   2, ARRAY['extended']::text[], 6, true, 207, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.07'),
  ('stone_harbor','en','dad',
   'Tell me about the day you first understood your mother had been a girl once.',
   2, ARRAY['mother']::text[], 7, false, 208, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.08'),
  ('stone_harbor','en','dad',
   'Tell me about a moment your mother surprised you — for better, or for worse.',
   2, ARRAY['mother']::text[], 5, true, 209, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.09'),
  ('stone_harbor','en','dad',
   'The first friend who was different from you. What that difference taught you.',
   2, ARRAY['friendship']::text[], 6, true, 210, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.10'),
  ('stone_harbor','en','dad',
   'Tell me about a teacher who saw you. What did they see?',
   2, ARRAY['outside']::text[], 6, true, 211, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.11'),
  ('stone_harbor','en','dad',
   'Write about a stranger — a coach, a neighbor, a friend''s parent — whose impression on you outlasted theirs of you.',
   2, ARRAY['outside']::text[], 5, true, 212, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.12'),
  ('stone_harbor','en','dad',
   'What were you secretly proud of as a boy? What didn''t you tell anyone?',
   2, ARRAY['self']::text[], 5, true, 213, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.13'),
  ('stone_harbor','en','dad',
   'Tell me about the moment you realized adults were not always right.',
   2, ARRAY['formation']::text[], 5, false, 214, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.14'),
  ('stone_harbor','en','dad',
   'The smell that comes back without warning. Where it takes you.',
   2, ARRAY['memory']::text[], 4, true, 215, 'Dad_Story_Series_Prompt_Pool_v1.md#L2.15'),

  -- ===== Level 3 — Channel =====
  ('stone_harbor','en','dad',
   'Write about the time you understood your body was not invincible.',
   3, ARRAY['body']::text[], 6, false, 301, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.01'),
  ('stone_harbor','en','dad',
   'The boy who knew you best when you were nine. Where is he now?',
   3, ARRAY['friendship']::text[], 7, false, 302, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.02'),
  ('stone_harbor','en','dad',
   'Tell me about a time you were told you were too much — too loud, too sensitive, too tall, too late. What you did with that.',
   3, ARRAY['wounds','self']::text[], 8, true, 303, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.03'),
  ('stone_harbor','en','dad',
   'Tell me about a punishment you remember. What it taught you to do — and what it taught you to hide.',
   3, ARRAY['formation','wounds']::text[], 7, true, 304, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.04'),
  ('stone_harbor','en','dad',
   'Write about a time your father was tender. If he was.',
   3, ARRAY['father']::text[], 6, true, 305, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.05'),
  ('stone_harbor','en','dad',
   'What did your father say without saying it?',
   3, ARRAY['father']::text[], 6, false, 306, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.06'),
  ('stone_harbor','en','dad',
   'Tell me about the first time you wanted to protect your father.',
   3, ARRAY['father']::text[], 6, false, 307, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.07'),
  ('stone_harbor','en','dad',
   'The thing your siblings knew about you that your parents never did.',
   3, ARRAY['siblings']::text[], 5, true, 308, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.08'),
  ('stone_harbor','en','dad',
   'Who got the most attention in the house. What the rest of you did with that.',
   3, ARRAY['siblings']::text[], 6, false, 309, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.09'),
  ('stone_harbor','en','dad',
   'The friend''s house that felt safer than yours. If there was one.',
   3, ARRAY['friendship']::text[], 6, false, 310, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.10'),
  ('stone_harbor','en','dad',
   'The first time you lied and felt the lie sit in your stomach.',
   3, ARRAY['formation']::text[], 5, true, 311, 'Dad_Story_Series_Prompt_Pool_v1.md#L3.11'),

  -- ===== Level 4 — Open Water =====
  ('stone_harbor','en','dad',
   'Tell me, if you can, about the first time you noticed your parents were not happy.',
   4, ARRAY['wounds','mother','father']::text[], 10, false, 401, 'Dad_Story_Series_Prompt_Pool_v1.md#L4.01'),
  ('stone_harbor','en','dad',
   'The first thing you remember being ashamed of. Tell me what shape it took.',
   4, ARRAY['wounds','self']::text[], 8, false, 402, 'Dad_Story_Series_Prompt_Pool_v1.md#L4.02'),
  ('stone_harbor','en','dad',
   'A memory you''ve never been sure was real. Write it anyway.',
   4, ARRAY['memory']::text[], 7, true, 403, 'Dad_Story_Series_Prompt_Pool_v1.md#L4.03');

-- Verification (run manually after migration):
--   select depth, count(*) from public.story_prompts where series_slug='dad' group by depth order by depth;
-- Expected: 1→7, 2→15, 3→11, 4→3, total 36.
